# -*- coding: utf-8 -*-
"""SamsonovENN1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0cr6Wq9Bj25mQQQFmF992Lu9u_EE3Pv

ran in gooogle colab with 15gb T4 gpu
added S=1024 B=512 config to cause an OOM

# check nvidia-smi + imports + misc setip
"""

!nvidia-smi

import csv
import statistics
import subprocess
import threading
import time
import itertools
from pathlib import Path
import random

import torch
import torch.nn as nn

torch.backends.cudnn.benchmark = False
torch.backends.cudnn.allow_tf32 = False
torch.backends.cuda.matmul.allow_tf32 = False

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
N_WARMUP = 5
N_TIMED = 20
RESULTS_DIR = Path("results")
MEASUREMENTS_CSV = RESULTS_DIR / "measurements.csv"

DEVICE

S_base = [32, 64, 128, 224, 256, 384, 512]  # added because T4 did not oom
B_base = [1, 2, 4, 8, 16, 32, 64, 128, 256]

random.seed(0)
S_RANDOM = random.sample([s for s in range(32, 513, 16) if s not in S_base], 4)
B_RANDOM = random.sample([b for b in range(1, 257) if b not in B_base and (b & (b - 1)) != 0], 3)  # non-power-of-two ints

S = sorted(S_base + S_RANDOM + [1024])
B = sorted(B_base + B_RANDOM + [512])

def is_validation(s, b):
    return s not in S_base or b not in B_base

"""added stuff from https://docs.pytorch.org/docs/2.14/notes/randomness.html"""

torch.manual_seed(42)
torch.use_deterministic_algorithms(True)

"""# the model"""

class SmallCNN(nn.Module):
    def __init__(self, num_classes: int = 100):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=7, stride=2, padding=7 // 2, bias=False),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2, padding=1),

            nn.Conv2d(32, 64, kernel_size=5, stride=1, padding=5 // 2, bias=False),
            nn.ReLU(inplace=True),

            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=3 // 2, bias=False),
            nn.ReLU(inplace=True),

            nn.Conv2d(128, 256, kernel_size=1, stride=1, padding=1 // 2, bias=False),
            nn.ReLU(inplace=True),

            nn.Conv2d(256, 256, kernel_size=3, stride=2, padding=3 // 2, bias=False),
            nn.ReLU(inplace=True),

            nn.Conv2d(256, 512, kernel_size=1, stride=1, padding=1 // 2, bias=False),
            nn.ReLU(inplace=True),
        )
        self.head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Linear(256, num_classes),
        )

    def forward(self, x):
        x = self.features(x)
        return self.head(x)

def _make_input(s: int, b: int) -> torch.Tensor:
    return torch.randn(b, 3, s, s, device=DEVICE, dtype=torch.float32)


def _time_forward(model: torch.nn.Module, x: torch.Tensor, n_iters: int) -> list[float]:
    times = []
    with torch.inference_mode():
        for _ in range(n_iters):
            torch.cuda.synchronize()
            start = time.perf_counter()
            model(x)
            torch.cuda.synchronize()
            times.append(time.perf_counter() - start)
    return times

"""# measure toolkit"""

class PowerSampler:
    "samples power draw from different thread"
    def __init__(self, interval: float = 0.02):
        self.interval = interval
        self._samples: list[float] = []
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None

    def _run(self):
        cmd = [
            "nvidia-smi",
            f"--id=0",
            "--query-gpu=power.draw",
            "--format=csv,noheader,nounits",
        ]
        while not self._stop.is_set():
            try:
                out = subprocess.check_output(cmd, timeout=1.0).decode().strip()
                self._samples.append(float(out))
            except Exception:
                pass
            time.sleep(self.interval)

    def __enter__(self) -> "PowerSampler":
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *exc_info):
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=1.0)

    def average_watts(self) -> float:
        return statistics.mean(self._samples) if self._samples else float("nan")

def measure_one(model: torch.nn.Module, s: int, b: int) -> tuple[float, int, float]:
    x = _make_input(s, b)

    _time_forward(model, x, N_WARMUP)  # warm-up, not measured

    torch.cuda.synchronize()
    torch.cuda.reset_peak_memory_stats()

    with PowerSampler() as sampler:
        start = time.perf_counter()
        times = _time_forward(model, x, N_TIMED)
        elapsed = time.perf_counter() - start

    latency_s = statistics.median(times)
    memory_bytes = torch.cuda.max_memory_allocated()
    energy_j = sampler.average_watts() * elapsed / N_TIMED

    del x
    torch.cuda.empty_cache()
    return latency_s, memory_bytes, energy_j

"""# the run"""

RESULTS_DIR.mkdir(parents=True, exist_ok=True)
model = SmallCNN().to(DEVICE).eval()

rows = []
for s, b in itertools.product(S, B):
    torch.cuda.empty_cache()
    try:
        latency_s, memory_bytes, energy_j = measure_one(model, s, b)
        rows.append(
            {
                "S": s,
                "B": b,
                "latency": latency_s,
                "memory": memory_bytes,
                "energy": energy_j,
                "is_validation": is_validation(s, b),

            }
        )
        print(f"S={s:4d} B={b:4d}")
    except torch.cuda.OutOfMemoryError:
        torch.cuda.empty_cache()
        rows.append(
            {
                "S": s,
                "B": b,
                "latency": "",
                "memory": "OOM",
                "energy": "",
                "is_validation": is_validation(s, b),

            }
        )
        print(f"S={s:4d} B={b:4d}  OOM")

with open(MEASUREMENTS_CSV, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["S", "B", "latency", "memory", "energy", "is_validation"])
    writer.writeheader()
    writer.writerows(rows)

