# -*- coding: utf-8 -*-
"""SamsonovENN2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AS8SOCnJCuW1u1DVQS4vZwuewZRhvizM

# Environment
"""

import copy
import gc
import json
import math
import os
import platform
import sys
import tempfile
import time
import warnings
from functools import partial
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from sklearn.model_selection import train_test_split
from torch.optim.lr_scheduler import (
    ChainedScheduler, LambdaLR, LinearLR, MultiplicativeLR, MultiStepLR, OneCycleLR, SequentialLR,
)
from torch.utils.data import BatchSampler, DataLoader, RandomSampler, SequentialSampler, Subset, TensorDataset
from torchvision.models.resnet import BasicBlock, conv3x3
from torchvision.transforms import v2

from google.colab import drive

drive.mount("/content/drive")
ROOT = Path("/content/drive/MyDrive/enn-superconvergence")

DATA = Path("data")
RESULTS = ROOT / "results"
CKPT = ROOT / "checkpoints"
INDICES = ROOT / "indices"

for d in (DATA, RESULTS, CKPT, INDICES):
    d.mkdir(parents=True, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.backends.cudnn.benchmark = False

# seed for data sampling. ALways constant
INDEX_SEED = 0
MAX_SAFE_LR_SLOPE = 1e-3

# seed for model training, may change
seed = 42

env = dict(
        python=sys.version.split()[0],
        platform=platform.platform(),
        torch=torch.__version__,
        torchvision=torchvision.__version__,
        cuda=torch.version.cuda,
        cudnn=torch.backends.cudnn.version(),
        device=torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu",
    )

print(*env.items(), sep="\n")

"""# stuff wrappers

Will make running the experiments a bit easier

"""

!nvidia-smi

CIFAR_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR_STD = (0.2470, 0.2435, 0.2616)
CIFAR_AUGMENT = v2.Compose([v2.RandomCrop(32, padding=4), v2.RandomHorizontalFlip()])


def load_cifar10():
    to_input = [v2.ToImage(), v2.ToDtype(torch.float32, scale=True), v2.Normalize(CIFAR_MEAN, CIFAR_STD)]
    train = torchvision.datasets.CIFAR10(
        DATA, train=True, download=True, transform=v2.Compose([v2.ToImage(), CIFAR_AUGMENT, *to_input[1:]])
    )
    test = torchvision.datasets.CIFAR10(DATA, train=False, download=True, transform=v2.Compose(to_input))
    return train, test

def load_mnist():
    to_input = v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32), v2.Normalize([0.0], [256.0])])
    train = torchvision.datasets.MNIST(DATA, train=True, download=True, transform=to_input)
    test = torchvision.datasets.MNIST(DATA, train=False, download=True, transform=to_input)
    return train, test

def subset_indices(ds, n, tag):
    path = INDICES / f"{tag}_{n}_seed{INDEX_SEED}.pt"
    if not path.exists():
        idx, _ = train_test_split(
            np.arange(len(ds.targets)), train_size=n, stratify=ds.targets, random_state=INDEX_SEED
        )
        torch.save(torch.as_tensor(np.sort(idx)), path)

    return torch.load(path).tolist()

def make_loader(ds, bs, train, seed=0):
    sampler = RandomSampler(ds, generator=torch.Generator()) if train else None
    return DataLoader(
        ds, batch_size=bs, sampler=sampler, drop_last=train, num_workers=os.cpu_count(), pin_memory=True,
        persistent_workers=True, generator=torch.Generator().manual_seed(seed),
    )

def batches(loader, seed, start_it=0):
    shuffle = getattr(loader.sampler, "sampler", loader.sampler)
    epoch, skip = divmod(start_it, len(loader))
    while True:
        shuffle.generator.manual_seed(seed * 100_003 + epoch)
        for i, (x, y) in enumerate(loader):
            if i >= skip:
                yield (x.to(device, non_blocking=True, memory_format=torch.channels_last),
                       y.to(device, non_blocking=True))
        epoch, skip = epoch + 1, 0

# had issues with LR ramping too fast with one cycle shcedule

def smooth_ramp(x):
    x = min(max(x, 0.0), 1.0)
    return x * x / (x * x + (1 - x) ** 2)

"""# models"""

def cifar_resnet(depth, num_classes=10, bn_momentum=0.05, zero_init_last_bn=False):
    n = (depth - 2) // 6
    norm = partial(nn.BatchNorm2d, momentum=bn_momentum)
    layers = [conv3x3(3, 16), norm(16), nn.ReLU(inplace=True)]
    c_in = 16
    for c_out in (16, 32, 64):
        for _ in range(n):
            stride = 1 if c_in == c_out else 2
            shortcut = None if stride == 1 else nn.Sequential(
                nn.AvgPool2d(2), nn.ZeroPad3d((0, 0, 0, 0, 0, c_out - c_in))
            )
            layers.append(BasicBlock(c_in, c_out, stride, shortcut, norm_layer=norm))
            c_in = c_out
    layers += [nn.AdaptiveAvgPool2d(1), nn.Flatten(), nn.Linear(64, num_classes)]
    model = nn.Sequential(*layers)

    for m in model.modules():
        if isinstance(m, nn.Conv2d):
            nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")
        if zero_init_last_bn and isinstance(m, BasicBlock):
            nn.init.zeros_(m.bn2.weight)
    return model

def lenet(num_classes=10):
    model = nn.Sequential(
        nn.Conv2d(1, 20, 5), nn.MaxPool2d(2), nn.Conv2d(20, 50, 5), nn.MaxPool2d(2), nn.Flatten(),
        nn.Linear(800, 500), nn.ReLU(), nn.Linear(500, num_classes),
    )

    for m in model:
        if isinstance(m, (nn.Conv2d, nn.Linear)):
            a = math.sqrt(3.0 / m.weight[0].numel())
            nn.init.uniform_(m.weight, -a, a)
            nn.init.zeros_(m.bias)
    return model

def sgd(model, lr=0.1, momentum=0.9, wd=1e-4):
    return torch.optim.SGD(
        [dict(params=[p for p in model.parameters() if p.ndim > 1], weight_decay=wd),
         dict(params=[p for p in model.parameters() if p.ndim <= 1], weight_decay=0.0)],
        lr=lr, momentum=momentum,
    )

"""# Schedules"""

def one_cycle(opt, total, lr_min, lr_max, cycle_frac=0.9, final_div=100.0, m_min=0.85, m_max=0.95,
              max_slope=MAX_SAFE_LR_SLOPE, min_warmup=100):
    sched = OneCycleLR(
        opt, max_lr=lr_max, total_steps=total, pct_start=cycle_frac / 2, anneal_strategy="linear",
        div_factor=lr_max / lr_min, final_div_factor=final_div, three_phase=True,
        base_momentum=m_min, max_momentum=m_max,
    )
    slope = (lr_max - lr_min) / (cycle_frac * total / 2)
    if slope <= max_slope:
        return sched
    warmup = max(min_warmup, math.ceil(2 * lr_min / max_slope))
    warnings.warn(
        f"1cycle ramp {lr_min} -> {lr_max} over {int(cycle_frac * total / 2)} its is {slope:.2e} lr/it "
        f"(safe: {max_slope:.0e}); adding a {warmup}-it smooth warm-up"
    )

    return ChainedScheduler([sched, MultiplicativeLR(opt, lambda it: smooth_ramp(it / warmup))])

def piecewise_constant(opt, total, lr0, milestones=(0.5, 0.75), gamma=0.1, warmup=0):

    for g in opt.param_groups:
        g["lr"] = lr0
    steps = [int(m * total) for m in milestones]
    if not warmup:
        return MultiStepLR(opt, steps, gamma)
    return SequentialLR(
        opt, [LinearLR(opt, start_factor=1 / warmup, total_iters=warmup),
              MultiStepLR(opt, [s - warmup for s in steps], gamma)],
        milestones=[warmup],
    )

class LrEstimator:
    # The paper's hessian-free LR estimator
    def __init__(self, mode="every", first=300, every=10, alpha=0.1):
        assert mode in ("every", "sparse")
        self.mode, self.first, self.every, self.alpha = mode, first, every, alpha
        self.buf = []
        self.trace = []
        self.ema = None

    def _wanted(self, j):
        if self.mode == "every":
            return j <= self.first + 2
        return j >= self.every and j % self.every < 3

    def __call__(self, it, model, lr, step_ok):
        j = it + 1
        if not step_ok:
            self.buf.clear()
            return
        if not self._wanted(j):
            return
        if self.buf and self.buf[-1][0] != j - 1:
            self.buf.clear()

        self.buf.append((j, torch.cat([p.detach().reshape(-1) for p in model.parameters()]), lr))
        if len(self.buf) < 3:
            return
        (i, w0, _), (_, w1, lr0), (_, w2, lr1) = self.buf
        d1, d2 = w1 - w0, w2 - w1
        est = (d1.abs().sum() / (d1 / lr0 - d2 / lr1).abs().sum()).item()
        self.ema = est if self.ema is None else self.alpha * est + (1 - self.alpha) * self.ema
        self.trace.append((i, est, self.ema))
        if self.mode == "every":
            self.buf.pop(0)
        else:
            self.buf.clear()

    def state_dict(self):
        return dict(trace=self.trace, ema=self.ema)

    def load_state_dict(self, state):
        self.trace, self.ema, self.buf = state["trace"], state["ema"], []

"""# training"""

def run_name(cfg, keys=("model", "depth", "n_train", "sched", "lr_hi", "lr0", "wd", "bs", "iters", "seed")):
    return cfg["exp"] + "/" + "_".join(f"{k}{cfg[k]}" for k in keys if k in cfg)

@torch.no_grad()
def evaluate(model, loader, train_mode=False):
    was_training = model.training
    if train_mode:
        model = copy.deepcopy(model)
    model.train(train_mode)
    loss_sum = torch.zeros((), device=device)
    correct = torch.zeros((), device=device)
    for x, y in loader:
        x = x.to(device, non_blocking=True, memory_format=torch.channels_last)
        y = y.to(device, non_blocking=True)
        logits = model(x).float()
        loss_sum += F.cross_entropy(logits, y, reduction="sum")
        correct += (logits.argmax(1) == y).sum()
    model.train(was_training)
    n = len(loader.dataset)
    return loss_sum.item() / n, correct.item() / n

def train(name, cfg, model, opt, sched, train_loader, eval_loader, final_loader, hooks=(), stop_at=None, root=ROOT):
    """Train for cfg["iters"] iterations with AMP and return the result dict.

    stop_at: checkpoint and return None at the first eval at or after this iteration (session budget).
    """
    res_path = root / "results" / f"{name}.json"
    ckpt_path = root / "checkpoints" / f"{name}.pt"
    if res_path.exists():
        print(f"[{name}] already done, loading the result")
        return json.loads(res_path.read_text())
    res_path.parent.mkdir(parents=True, exist_ok=True)
    ckpt_path.parent.mkdir(parents=True, exist_ok=True)

    total = cfg["iters"]
    scaler = torch.amp.GradScaler("cuda")
    losses = torch.full((total,), float("nan"), device=device)
    state = dict(it=0, history=[], flags=[], t_train=0.0, t_eval=0.0)
    stateful = dict(model=model, opt=opt, sched=sched, scaler=scaler) | {f"hook{i}": h for i, h in enumerate(hooks)}
    if ckpt_path.exists():
        ck = torch.load(ckpt_path, map_location=device, weights_only=False)
        for key, obj in stateful.items():
            obj.load_state_dict(ck[key])
        state = ck["state"]
        losses[:state["it"]] = ck["losses"]
        print(f"[{name}] resumed at it {state['it']}")

    win = torch.zeros(3, device=device)
    status = "complete"
    model.train()
    data = batches(train_loader, cfg["seed"], state["it"])
    t0 = time.perf_counter()
    for it in range(state["it"], total):
        x, y = next(data)
        lr = opt.param_groups[0]["lr"]
        mom = opt.param_groups[0]["momentum"]

        with torch.autocast("cuda", dtype=torch.float16):
            logits = model(x)
            loss = F.cross_entropy(logits, y)
        opt.zero_grad(set_to_none=True)
        scale_before = scaler.get_scale() if hooks else None
        scaler.scale(loss).backward()
        scaler.step(opt)
        scaler.update()
        sched.step()

        loss = loss.detach().float()
        losses[it] = loss
        win += torch.stack([loss.nan_to_num(0.0, 0.0, 0.0), loss.isfinite().float(),
                           (logits.argmax(1) == y).sum().float()])
        for h in hooks:
            h(it, model, lr, scaler.get_scale() >= scale_before)

        if (it + 1) % cfg["eval_every"] and it + 1 < total:
            continue

        # eval
        torch.cuda.synchronize()
        t1 = time.perf_counter()
        state["t_train"] += t1 - t0
        loss_sum, finite_steps, correct = win.tolist()
        win.zero_()
        steps = it + 1 - (state["history"][-1]["it"] if state["history"] else 0)
        row = dict(
            it=it + 1, lr=lr, momentum=mom, train_loss=loss_sum / max(finite_steps, 1),
            train_acc=correct / (steps * len(y)), nonfinite=steps - int(finite_steps),
        )
        row["test_loss"], row["test_acc"] = evaluate(model, eval_loader)
        if cfg.get("log_train_mode"):
            row["test_acc_trainmode"] = evaluate(model, eval_loader, train_mode=True)[1]
        state["t_eval"] += time.perf_counter() - t1
        row["t_train"], row["t_eval"] = state["t_train"], state["t_eval"]
        state["history"].append(row)
        print(f"[{name}] " + " ".join(f"{k} {v:.4g}" for k, v in row.items()))

        # collapse
        if abs(row["train_loss"] - math.log(cfg["n_classes"])) < 0.05 and row["train_acc"] < 1.5 / cfg["n_classes"]:
            state["flags"].append(f"collapsed@{it + 1}")
        # divirged
        weights = torch.cat([t.flatten() for t in model.state_dict().values() if t.is_floating_point()])
        if not weights.isfinite().all() or row["nonfinite"] > steps / 2:
            status = "diverged"
            state["flags"].append(f"diverged@{it + 1}")
            break

        state["it"] = it + 1
        if (it + 1) % cfg["ckpt_every"] == 0 or (stop_at is not None and it + 1 >= stop_at):
            torch.save({k: obj.state_dict() for k, obj in stateful.items()} | dict(state=state, losses=losses[:it + 1]),
                       ckpt_path)
        if stop_at is not None and it + 1 >= stop_at and it + 1 < total:
            print(f"[{name}] stopped at it {it + 1}, rerun to resume")
            return None
        t0 = time.perf_counter()

    final_loss, final_acc = evaluate(model, final_loader)
    accs = [r["test_acc"] for r in state["history"]]
    result = dict(
        name=name, cfg=cfg, env=env, status=status, flags=state["flags"], history=state["history"],
        final=dict(
            test_loss=final_loss, test_acc=final_acc, best_eval_acc=max(accs),
            mean_last3_eval_acc=float(np.mean(accs[-3:])), t_train=state["t_train"], t_eval=state["t_eval"],
        ),
        hooks=[h.state_dict() for h in hooks],
    )
    np.save(root / "results" / f"{name}.losses.npy", losses.cpu().numpy())
    res_path.write_text(json.dumps(result, indent=1))
    ckpt_path.unlink(missing_ok=True)
    print(f"[{name}] {status}: final test acc {final_acc:.4f}, flags {state['flags']}")
    return result

"""# startup"""

cifar_train, cifar_test = load_cifar10()
mnist_train, mnist_test = load_mnist()

for name, ds in (("cifar10 train", cifar_train), ("cifar10 test", cifar_test),
                 ("mnist train", mnist_train), ("mnist test", mnist_test)):
    x, y = ds[0]
    print(f"{name}: {len(ds)} samples, x {tuple(x.shape)} {x.dtype}, y {y}")

fig, axes = plt.subplots(2, 8, figsize=(12, 3.2))
for i in range(8):
    axes[0, i].imshow(cifar_train.data[i])
    axes[1, i].imshow((cifar_train[i][0]).clamp(0, 1).permute(1, 2, 0))
    axes[0, i].axis("off")
    axes[1, i].axis("off")
axes[0, 0].set_title("original", loc="left")
axes[1, 0].set_title("augmented", loc="left")
plt.tight_layout()
plt.show()

loader = make_loader(cifar_train, 512, train=True, seed=seed)
stream = batches(loader, seed)

def schedule_trace(build, total):
    opt = torch.optim.SGD([torch.zeros(1, requires_grad=True)], lr=1.0, momentum=0.9)
    sched = build(opt)
    lrs, moms = [], []
    for _ in range(total):
        lrs.append(opt.param_groups[0]["lr"])
        moms.append(opt.param_groups[0]["momentum"])
        opt.step()
        sched.step()
    return np.array(lrs), np.array(moms)

"""# Smoke"""

smoke_root = Path(tempfile.mkdtemp(prefix="sc_smoke_"))
eval_loader = make_loader(Subset(cifar_test, subset_indices(cifar_test, 2000, "cifar10_test")), 1000, train=False)

cfg = dict(exp="smoke", model="resnet", depth=20, sched="1cycle", lr_hi=1.0, wd=1e-4, bs=512, iters=300,
           seed=seed, eval_every=100, ckpt_every=100, n_classes=10, log_train_mode=True)
torch.manual_seed(cfg["seed"])
model = cifar_resnet(20).to(device, memory_format=torch.channels_last)
opt = sgd(model, wd=cfg["wd"])
res = train(
    run_name(cfg), cfg, model, opt, one_cycle(opt, cfg["iters"], 0.1, cfg["lr_hi"]),
    make_loader(cifar_train, cfg["bs"], train=True, seed=cfg["seed"]), eval_loader, eval_loader, root=smoke_root,
)

cfg = dict(exp="smoke", model="lenet", sched="inv", lr0=0.01, wd=5e-4, bs=512, iters=300, seed=seed,
           eval_every=100, ckpt_every=1000, n_classes=10)
torch.manual_seed(cfg["seed"])
model = lenet().to(device)
opt = sgd(model, lr=cfg["lr0"], wd=cfg["wd"])
mnist_test_loader = make_loader(mnist_test, 1000, train=False)
res = train(
    run_name(cfg), cfg, model, opt, LambdaLR(opt, lambda it: (1 + 1e-4 * it) ** -0.75),
    make_loader(mnist_train, cfg["bs"], train=True, seed=cfg["seed"]), mnist_test_loader, mnist_test_loader,
    root=smoke_root,
)

stream = batches(make_loader(cifar_train, 512, train=True, seed=seed), seed)
fixed = next(stream)
for depth in (20, 56, 110):
    m = cifar_resnet(depth).to(device, memory_format=torch.channels_last)
    opt = sgd(m)
    scaler = torch.amp.GradScaler("cuda")
    timings = []
    for get_batch in (lambda: fixed, lambda: next(stream)):
        for it in range(80):
            if it == 30:
                torch.cuda.synchronize()
                t = time.perf_counter()
            x, y = get_batch()
            with torch.autocast("cuda", dtype=torch.float16):
                loss = F.cross_entropy(m(x), y)
            opt.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()
        torch.cuda.synchronize()
        timings.append((time.perf_counter() - t) / 50)
    print(f"ResNet-{depth}: {timings[0]:.3f} s/it model only, {timings[1]:.3f} s/it with loader")

"""basically the data loader halves the performance"""

del loader, stream, x, y, m, opt
del model, res, eval_loader, mnist_test_loader
gc.collect()
torch.cuda.empty_cache()

stream = batches(make_loader(cifar_train, 512, train=True, seed=seed), seed)
fixed = next(stream)
for depth in (20, 56, 110):
    m = cifar_resnet(depth).to(device, memory_format=torch.channels_last)
    opt = sgd(m)
    scaler = torch.amp.GradScaler("cuda")
    timings = []
    for get_batch in (lambda: fixed, lambda: next(stream)):
        for it in range(80):
            if it == 30:
                torch.cuda.synchronize()
                t = time.perf_counter()
            x, y = get_batch()
            with torch.autocast("cuda", dtype=torch.float16):
                loss = F.cross_entropy(m(x), y)
            opt.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()
        torch.cuda.synchronize()
        timings.append((time.perf_counter() - t) / 50)
    print(f"ResNet-{depth}: {timings[0]:.3f} s/it model only, {timings[1]:.3f} s/it with loader")

del stream, fixed, m, opt, scaler, x, y, loss
gc.collect()
torch.cuda.empty_cache()

cifar_normalize = v2.Normalize(CIFAR_MEAN, CIFAR_STD)

def random_crop_flip(x, pad=4):
    b, _, h, w = x.shape
    theta = torch.zeros(b, 2, 3, device=x.device)
    theta[:, 0, 0] = torch.randint(0, 2, (b,), device=x.device) * 2 - 1
    theta[:, 1, 1] = 1

    theta[:, :, 2] = torch.randint(-pad, pad + 1, (b, 2), device=x.device) * 2 / torch.tensor([w, h], device=x.device)
    grid = F.affine_grid(theta, list(x.shape), align_corners=False)
    return F.grid_sample(x, grid, mode="nearest", padding_mode="zeros", align_corners=False)


def cifar_augment(x):
    return cifar_normalize(random_crop_flip(x))


def cifar_to_gpu(ds):
    x = torch.as_tensor(ds.data, device=device).permute(0, 3, 1, 2).float().div(255)
    return x, torch.as_tensor(ds.targets, device=device)

x, y = cifar_to_gpu(cifar_train)
gpu_cifar_train = TensorDataset(x, y)
x, y = cifar_to_gpu(cifar_test)
gpu_cifar_test = TensorDataset(cifar_normalize(x), y)
gpu_mnist_train = TensorDataset(mnist_train.data.to(device).unsqueeze(1).float().div(256), mnist_train.targets.to(device))
gpu_mnist_test = TensorDataset(mnist_test.data.to(device).unsqueeze(1).float().div(256), mnist_test.targets.to(device))
del x, y

def make_gpu_loader(ds, bs, train, augment=None):
    order = RandomSampler(ds, generator=torch.Generator()) if train else SequentialSampler(ds)
    return DataLoader(
        ds, batch_size=None, sampler=BatchSampler(order, bs, drop_last=train),
        collate_fn=(lambda batch: (augment(batch[0]), batch[1])) if augment else None,
    )

stream = batches(make_gpu_loader(gpu_cifar_train, 512, train=True, augment=cifar_augment), seed)
fixed = next(stream)
for depth in (20, 56, 110):
    m = cifar_resnet(depth).to(device, memory_format=torch.channels_last)
    opt = sgd(m)
    scaler = torch.amp.GradScaler("cuda")
    timings = []
    for get_batch in (lambda: fixed, lambda: next(stream)):
        for it in range(80):
            if it == 30:
                torch.cuda.synchronize()
                t = time.perf_counter()
            x, y = get_batch()
            with torch.autocast("cuda", dtype=torch.float16):
                loss = F.cross_entropy(m(x), y)
            opt.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()
        torch.cuda.synchronize()
        timings.append((time.perf_counter() - t) / 50)
    print(f"ResNet-{depth}: {timings[0]:.3f} s/it model only, {timings[1]:.3f} s/it with loader")

stream = batches(make_gpu_loader(gpu_mnist_train, 512, train=True), seed)
m = lenet().to(device)
opt = sgd(m, lr=0.01, wd=5e-4)
scaler = torch.amp.GradScaler("cuda")
for it in range(230):
    if it == 30:
        torch.cuda.synchronize()
        t = time.perf_counter()
    x, y = next(stream)
    with torch.autocast("cuda", dtype=torch.float16):
        loss = F.cross_entropy(m(x), y)
    opt.zero_grad(set_to_none=True)
    scaler.scale(loss).backward()
    scaler.step(opt)
    scaler.update()
torch.cuda.synchronize()
print(f"LeNet: {(time.perf_counter() - t) / 200:.4f} s/it with loader (was 0.138)")

t = time.perf_counter()
evaluate(m, make_gpu_loader(gpu_mnist_test, 1000, train=False))
print(f"LeNet eval on the 10k MNIST test set: {time.perf_counter() - t:.2f} s (was 4.3)")

del stream, fixed, m, opt, scaler, x, y, loss
gc.collect()
torch.cuda.empty_cache()

"""# the actual experiments"""

SEEDS = (42,66,35076126)

eval_subset = TensorDataset(*gpu_cifar_test[subset_indices(cifar_test, 2000, "cifar10_test")])


def rounded(v):
    if isinstance(v, dict):
        return {k: rounded(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [rounded(x) for x in v]
    return round(float(v), 4) if isinstance(v, (float, np.floating)) else v


def record_decision(key, **values):
    path = RESULTS / "decisions.json"
    decisions = json.loads(path.read_text()) if path.exists() else {}
    decisions[key] = rounded(values)
    path.write_text(json.dumps(decisions, indent=1))
    print(key, json.dumps(decisions[key], indent=1))


def mean_history(results):
    return pd.concat([pd.DataFrame(r["history"]) for r in results]).groupby("it").mean(numeric_only=True)

"""## experiment 1

LR range test up to 3, not stopping at lr .1

Expected to see more or less stable numbers when LR grows, no abnorbal blowups

note to not apply large LR at first iterations, else models converges to predicting one output
"""

results = []
for s in SEEDS:
    cfg = dict(exp="range_test", model="resnet", depth=56, n_train=50_000, sched="range", lr_hi=3.0, wd=1e-4,
               bs=512, iters=8000, seed=s, eval_every=100, ckpt_every=1000, n_classes=10, log_train_mode=True)
    torch.manual_seed(s)
    model = cifar_resnet(cfg["depth"], bn_momentum=0.05).to(device, memory_format=torch.channels_last)
    opt = sgd(model, lr=cfg["lr_hi"], momentum=0.9, wd=cfg["wd"])
    results.append(train(
        run_name(cfg), cfg, model, opt, LinearLR(opt, start_factor=1e-4, total_iters=cfg["iters"] - 1),
        make_gpu_loader(gpu_cifar_train, cfg["bs"], train=True, augment=cifar_augment),
        make_gpu_loader(eval_subset, 1000, train=False),
        make_gpu_loader(gpu_cifar_test, 1000, train=False),
    ))
    del model, opt

hist = mean_history(results)
smooth = hist[["test_acc", "test_acc_trainmode", "test_loss"]].rolling(5, center=True, min_periods=1).mean()

peak = smooth["test_acc"].max()
lr_at_peak = hist.loc[smooth["test_acc"].idxmax(), "lr"]
lr_max = hist.loc[smooth["test_acc"] >= 0.9 * peak, "lr"].max()
acc_at_end = smooth["test_acc"].iloc[-1]
flags = [f for r in results for f in r["flags"]]
c1 = all(r["status"] == "complete" for r in results) and not flags and acc_at_end >= 0.9 * peak

print(f"seeds {SEEDS}, flags {flags}")
print(f"peak smoothed acc {peak:.3f} at LR {lr_at_peak:.2f}")
print(f"smoothed acc at LR {hist['lr'].iloc[-1]:.2f}: {acc_at_end:.3f} ({acc_at_end / peak:.0%} of peak)")
print(f"lr_max (smoothed acc >= 90% of peak): {lr_max:.2f}")
print(f"C1 reproduced: {c1}")

record_decision(
    "resnet56_range_test", runs=[r["name"] for r in results], seeds=list(SEEDS),
    peak_acc=peak, lr_at_peak=lr_at_peak, peak_acc_trainmode=smooth["test_acc_trainmode"].max(),
    lr_max=lr_max, lr_max_censored=bool(lr_max >= cfg["lr_hi"] - 1e-6), acc_at_lr_hi=acc_at_end, c1=bool(c1),
)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(hist["lr"], hist["test_acc"], color="tab:blue", alpha=0.3, label="test acc (eval)")
axes[0].plot(hist["lr"], smooth["test_acc"], color="tab:blue", label="test acc, rolling mean 5")
axes[0].plot(hist["lr"], smooth["test_acc_trainmode"], color="tab:orange", label="test acc, BN in train mode")
axes[0].axhline(0.9 * peak, color="gray", ls=":", label="90% of peak")
axes[0].axvline(lr_max, color="gray", ls="--", label=f"lr_max = {lr_max:.2f}")
axes[0].set_xlabel("Learning rate")
axes[0].set_ylabel("Test accuracy")
axes[0].set_title("LR range test, ResNet-56, CIFAR-10 (Fig. 2b)")
axes[0].legend()

axes[1].plot(hist["lr"], hist["train_loss"], label="train loss")
axes[1].plot(hist["lr"], smooth["test_loss"], label="test loss, rolling mean 5")
axes[1].set_xlabel("Learning rate")
axes[1].set_ylabel("Loss")
axes[1].set_title("Train/test loss vs LR (Fig. 8a)")
axes[1].legend()
plt.tight_layout()
plt.show()

del results, hist, smooth
gc.collect()
torch.cuda.empty_cache()

"""## experiment 2

Use the hessian-free estimation over SGD and 1cycle. Mathces paper's statement on the hessian suggesting larger lrs
"""

results_pc, results_oc = [], []
for s in SEEDS:
    cfg = dict(exp="lr_estimator", model="resnet", depth=56, n_train=50_000, sched="pc", lr0=0.1, wd=1e-4,
               bs=512, iters=3000, seed=s, eval_every=100, ckpt_every=1000, n_classes=10)
    torch.manual_seed(s)
    model = cifar_resnet(cfg["depth"], bn_momentum=0.05).to(device, memory_format=torch.channels_last)
    opt = sgd(model, momentum=0.9, wd=cfg["wd"])
    results_pc.append(train(
        run_name(cfg), cfg, model, opt, piecewise_constant(opt, cfg["iters"], cfg["lr0"]),
        make_gpu_loader(gpu_cifar_train, cfg["bs"], train=True, augment=cifar_augment),
        make_gpu_loader(eval_subset, 1000, train=False),
        make_gpu_loader(gpu_cifar_test, 1000, train=False),
        hooks=[LrEstimator(mode="every", first=300), LrEstimator(mode="sparse", every=10)],
    ))
    del model, opt

    cfg = dict(exp="lr_estimator", model="resnet", depth=56, n_train=50_000, sched="1cycle", lr_hi=3.0, wd=1e-4,
               bs=512, iters=3000, seed=s, eval_every=100, ckpt_every=1000, n_classes=10)
    torch.manual_seed(s)
    model = cifar_resnet(cfg["depth"], bn_momentum=0.05).to(device, memory_format=torch.channels_last)
    opt = sgd(model, momentum=0.9, wd=cfg["wd"])
    results_oc.append(train(
        run_name(cfg), cfg, model, opt, one_cycle(opt, cfg["iters"], 0.1, cfg["lr_hi"]),
        make_gpu_loader(gpu_cifar_train, cfg["bs"], train=True, augment=cifar_augment),
        make_gpu_loader(eval_subset, 1000, train=False),
        make_gpu_loader(gpu_cifar_test, 1000, train=False),
        hooks=[LrEstimator(mode="every", first=300), LrEstimator(mode="sparse", every=10)],
    ))
    del model, opt

iters = cfg["iters"]
lr_pc, _ = schedule_trace(lambda o: piecewise_constant(o, iters, 0.1), iters)
lr_oc, _ = schedule_trace(lambda o: one_cycle(o, iters, 0.1, 3.0), iters)
runs = (("PC-LR 0.1 (classic)", results_pc, lr_pc), ("1cycle 0.1-3", results_oc, lr_oc))

for i, s in enumerate(SEEDS):
    fig, axes = plt.subplots(2, 2, figsize=(13, 8), sharey="row")
    for row, (label, results, lr_used) in enumerate(runs):
        for col, (trace, title) in enumerate(((results[i]["hooks"][0]["trace"], "every iteration, first 300 (Fig. 3a)"),
                                              (results[i]["hooks"][1]["trace"], "every 10 iterations (Fig. 3b)"))):
            it, est, ema = np.array(trace).T
            ax = axes[row, col]
            ax.plot(it, est, color="tab:blue", alpha=0.25, lw=0.8, label="estimate (Eq. 8)")
            ax.plot(it, ema, color="tab:blue", label="estimate, EMA α=0.1")
            ax.plot(np.arange(int(it.max()) + 1), lr_used[:int(it.max()) + 1], color="black", label="LR used")
            ax.set_yscale("log")
            ax.set_xlabel("Iteration")
            ax.set_ylabel("Learning rate")
            ax.set_title(f"{label}, seed {s}: {title}")
            ax.legend()
    plt.tight_layout()
    plt.show()

readout = {}
for label, results, lr_used in runs:
    early = np.concatenate([np.array(r["hooks"][0]["trace"]) for r in results])
    late = np.concatenate([np.array(r["hooks"][1]["trace"]) for r in results])
    phase = {}
    for a, b in ((0, 0.5), (0.5, 0.9), (0.9, 1.0)):
        m = (late[:, 0] >= a * iters) & (late[:, 0] < b * iters)
        phase[f"ema_{int(a * 100)}_{int(b * 100)}pct"] = float(np.median(late[m, 2]))
    readout[label] = dict(
        final_test_acc=float(np.mean([r["final"]["test_acc"] for r in results])),
        early_ema_median=float(np.median(early[:, 2])), **phase,
        est_over_lr=float(np.median(late[:, 1] / lr_used[late[:, 0].astype(int)])),
    )
    print(label, json.dumps(readout[label], indent=1))

pc, oc = readout["PC-LR 0.1 (classic)"], readout["1cycle 0.1-3"]
early_o1 = all(0.1 <= r["early_ema_median"] <= 10 for r in (pc, oc))
drops_classic = pc["ema_90_100pct"] < 0.5 * pc["ema_0_50pct"]
higher_1cycle = oc["ema_50_90pct"] > pc["ema_50_90pct"]
echoes_lr = 0.75 < oc["est_over_lr"] / pc["est_over_lr"] < 1.33
record_decision(
    "lr_estimator", seeds=list(SEEDS), pc=pc, one_cycle=oc,
    early_o1=bool(early_o1), drops_classic=bool(drops_classic), higher_1cycle=bool(higher_1cycle),
    early_in_paper_range_2_6=bool(all(2 <= r["early_ema_median"] <= 6 for r in (pc, oc))),
    echoes_lr=bool(echoes_lr),
    c9="inconclusive" if echoes_lr else bool(early_o1 and drops_classic and higher_1cycle),
)

del results_pc, results_oc, runs, results, readout, lr_pc, lr_oc, early, late
gc.collect()
torch.cuda.empty_cache()

"""eeeeee, we are meassuring the curvature along steepest descent and it tracks to close to the actual LR. Try re-implement the lr estimator with tighter sampling and warmup run"""

from collections import deque

def one_cycle_v2(opt, total, lr_min, lr_max, cycle_frac=0.9, final_div=100.0, m_min=0.85, m_max=0.95,
                 max_slope=MAX_SAFE_LR_SLOPE, min_warmup=100):
    sched = OneCycleLR(
        opt, max_lr=lr_max, total_steps=total, pct_start=cycle_frac / 2, anneal_strategy="linear",
        div_factor=lr_max / lr_min, final_div_factor=final_div, three_phase=True,
        base_momentum=m_min, max_momentum=m_max,
    )
    slope = (lr_max - lr_min) / (cycle_frac * total / 2)
    if slope <= max_slope:
        return sched
    warmup = max(min_warmup, math.ceil(2 * lr_min / max_slope))
    warnings.warn(
        f"1cycle ramp {lr_min} -> {lr_max} over {int(cycle_frac * total / 2)} its is {slope:.2e} lr/it "
        f"(safe: {max_slope:.0e}); adding a {warmup}-it smooth warm-up"
    )
    ramp = MultiplicativeLR(opt, lambda it: smooth_ramp(it / warmup))
    for g in opt.param_groups:
        g["lr"] *= smooth_ramp(0)
    return ChainedScheduler([sched, ramp])

class LrEstimatorV2:
    # second version, after experiment: the denominator from the real gradients
    def __init__(self, source="weights", stride=1, every=1, first=None, alpha=0.1):
        assert source in ("weights", "grads")
        self.source, self.stride, self.every, self.first, self.alpha = source, stride, every, first, alpha
        self.points = deque(maxlen=2 * stride + 1)
        self.pending = None
        self.trace = []
        self.ema = None

    def __call__(self, it, model, lr, step_ok):
        if self.first is not None and it > self.first + 2 * self.stride + 1:
            return
        if not step_ok:
            self.points.clear()
            self.pending = None
            return
        params = list(model.parameters())
        if self.pending is not None:

            grad = torch.cat([p.grad.detach().reshape(-1) for p in params]) if self.source == "grads" else None
            self.points.append((it, self.pending, grad, lr))
        self.pending = torch.cat([p.detach().reshape(-1) for p in params])
        if len(self.points) < self.points.maxlen:
            return

        (k, wa, ga, lra), (_, wb, gb, _), (_, wc, _, _) = self.points[0], self.points[self.stride], self.points[-1]
        if k % self.every or (self.first is not None and k >= self.first):
            return
        if self.source == "grads":
            est = ((wb - wa).abs().sum() / (gb - ga).abs().sum()).item()
        else:
            est = (lra * (wb - wa).abs().sum() / (2 * wb - wa - wc).abs().sum()).item()
        self.ema = est if self.ema is None else self.alpha * est + (1 - self.alpha) * self.ema
        self.trace.append((k, est, self.ema))

    def state_dict(self):
        return dict(trace=self.trace, ema=self.ema)

    def load_state_dict(self, state):
        self.trace, self.ema = state["trace"], state["ema"]
        self.points.clear()
        self.pending = None

VARIANTS_V2 = {
    "weights s1, dense": dict(source="weights", stride=1, every=1, first=300),
    "grads s1, dense": dict(source="grads", stride=1, every=1, first=300),
    "weights s1, /10": dict(source="weights", stride=1, every=10),
    "weights s10, /10": dict(source="weights", stride=10, every=10),
    "grads s10, /10": dict(source="grads", stride=10, every=10),
}
RUNS_2B = {
    "const 0.1, m 0.9": ("const", 0.9, lambda o, t: piecewise_constant(o, t, 0.1, milestones=())),
    "const 0.1, m 0": ("const_m0", 0.0, lambda o, t: piecewise_constant(o, t, 0.1, milestones=())),
    "PC-LR 0.1": ("pc", 0.9, lambda o, t: piecewise_constant(o, t, 0.1)),
    "1cycle 0.1-3 (v2)": ("1cycle", 0.9, lambda o, t: one_cycle_v2(o, t, 0.1, 3.0)),
}

results_2b = {label: [] for label in RUNS_2B}
for s in SEEDS:
    for label, (sched, momentum, build) in RUNS_2B.items():
        cfg = dict(exp="lr_estimator_v2", model="resnet", depth=56, n_train=50_000, sched=sched, wd=1e-4,
                   bs=512, iters=3000, seed=s, eval_every=100, ckpt_every=1000, n_classes=10)
        cfg["lr_hi" if sched == "1cycle" else "lr0"] = 3.0 if sched == "1cycle" else 0.1
        torch.manual_seed(s)
        model = cifar_resnet(cfg["depth"], bn_momentum=0.05).to(device, memory_format=torch.channels_last)
        opt = sgd(model, momentum=momentum, wd=cfg["wd"])
        results_2b[label].append(train(
            run_name(cfg), cfg, model, opt, build(opt, cfg["iters"]),
            make_gpu_loader(gpu_cifar_train, cfg["bs"], train=True, augment=cifar_augment),
            make_gpu_loader(eval_subset, 1000, train=False),
            make_gpu_loader(gpu_cifar_test, 1000, train=False),
            hooks=[LrEstimatorV2(**v) for v in VARIANTS_V2.values()],
        ))
        del model, opt

iters = cfg["iters"]
lr_2b = {label: schedule_trace(lambda o: build(o, iters), iters)[0] for label, (_, _, build) in RUNS_2B.items()}
lr_v1, _ = schedule_trace(lambda o: one_cycle(o, iters, 0.1, 3.0), iters)

fig, axes = plt.subplots(1, 2, figsize=(13, 4))
for ax, scale in zip(axes, ("linear", "log")):
    ax.plot(lr_v1, color="tab:gray", ls="--", label="1cycle (one_cycle, exp 2)")
    for label in ("PC-LR 0.1", "1cycle 0.1-3 (v2)"):
        ax.plot(lr_2b[label], label=label)
    ax.set_yscale(scale)
    ax.set_xlabel("Iteration")
    ax.set_ylabel("Learning rate")
    ax.set_title(f"LR schedules, {scale} axis")
    ax.legend()
plt.tight_layout()

colors = dict(zip(VARIANTS_V2, ("tab:blue", "tab:orange", "tab:blue", "tab:green", "tab:red")))
for i, s in enumerate(SEEDS):
    fig, axes = plt.subplots(len(RUNS_2B), 2, figsize=(13, 3.6 * len(RUNS_2B)))
    for row, label in enumerate(RUNS_2B):
        hooks = results_2b[label][i]["hooks"]
        for name, hook in zip(VARIANTS_V2, hooks):
            k, est, ema = np.array(hook["trace"]).T
            ax = axes[row, 0 if "dense" in name else 1]
            ax.plot(k, est, color=colors[name], alpha=0.15, lw=0.8)
            ax.plot(k, ema, color=colors[name], label=name)
        for col, n in enumerate((300, iters)):
            axes[row, col].plot(np.arange(n), lr_2b[label][:n], color="black", label="LR used")
            axes[row, col].set_yscale("log")
            axes[row, col].set_xlabel("Iteration")
            axes[row, col].set_ylabel("Learning rate")
            axes[row, col].set_title(f"{label}, seed {s}: " + ("first 300 (Fig. 3a)" if col == 0 else "every 10 (Fig. 3b)"))
            axes[row, col].legend(fontsize=8)
    plt.tight_layout()
    plt.show()

def median_ema(label, name, lo, hi):
    t = np.concatenate([np.array(r["hooks"][list(VARIANTS_V2).index(name)]["trace"]) for r in results_2b[label]])
    m = (t[:, 0] >= lo) & (t[:, 0] < hi)
    return float(np.median(t[m, 2])) if m.any() else float("nan")


def median_ratio(label, name):
    t = np.concatenate([np.array(r["hooks"][list(VARIANTS_V2).index(name)]["trace"]) for r in results_2b[label]])
    return float(np.median(t[:, 1] / np.maximum(lr_2b[label][t[:, 0].astype(int)], 1e-12)))


table = pd.DataFrame([
    dict(run=label, variant=name, early=median_ema(label, name, 0, 300), mid=median_ema(label, name, 0.5 * iters, 0.9 * iters),
         late=median_ema(label, name, 0.5 * iters, iters), est_over_lr=median_ratio(label, name),
         final_test_acc=float(np.mean([r["final"]["test_acc"] for r in results_2b[label]])))
    for label in RUNS_2B for name in VARIANTS_V2
])
print(table.round(4).to_string(index=False))

c9_by_variant = {}
for name in (n for n in VARIANTS_V2 if "dense" not in n):
    early = median_ema("const 0.1, m 0.9", name, 0, 300)
    late = median_ema("const 0.1, m 0.9", name, 0.5 * iters, iters)
    higher = median_ema("1cycle 0.1-3 (v2)", name, 0.5 * iters, 0.9 * iters) > median_ema("const 0.1, m 0.9", name, 0.5 * iters, 0.9 * iters)
    c9_by_variant[name] = dict(early_o1=bool(0.1 <= early <= 10), early_in_paper_range_2_6=bool(2 <= early <= 6),
                               drops_at_const_lr=bool(late < 0.5 * early), higher_1cycle=bool(higher),
                               c9=bool(0.1 <= early <= 10 and late < 0.5 * early and higher))
    print(name, c9_by_variant[name])

record_decision(
    "lr_estimator_v2", seeds=list(SEEDS), runs={label: [r["name"] for r in rs] for label, rs in results_2b.items()},
    table=table.to_dict(orient="records"), c9_by_variant=c9_by_variant,
)

del results_2b, lr_2b, lr_v1, table, c9_by_variant, hooks
gc.collect()
torch.cuda.empty_cache()



"""## mnist + lenet trains"""

MNIST_ITS_PER_EPOCH = len(gpu_mnist_train) // 512
mnist_test_loader = make_gpu_loader(gpu_mnist_test, 1000, train=False)

results = []
for s in SEEDS:
    cfg = dict(exp="range_test", model="lenet", sched="range", lr_hi=4.0, wd=5e-4, bs=512, iters=4000, seed=s,
               eval_every=100, ckpt_every=1000, n_classes=10)
    torch.manual_seed(s)
    model = lenet().to(device)
    opt = sgd(model, lr=cfg["lr_hi"], momentum=0.9, wd=cfg["wd"])
    results.append(train(
        run_name(cfg), cfg, model, opt, LinearLR(opt, start_factor=1e-4, total_iters=cfg["iters"] - 1),
        make_gpu_loader(gpu_mnist_train, cfg["bs"], train=True), mnist_test_loader, mnist_test_loader,
    ))
    del model, opt

hist = mean_history(results)
smooth = hist[["test_acc", "test_loss"]].rolling(5, center=True, min_periods=1).mean()
peak = smooth["test_acc"].max()
lr_max = hist.loc[smooth["test_acc"] >= 0.9 * peak, "lr"].max()
diverged_at = [r["history"][-1]["lr"] for r in results if r["status"] == "diverged"]

print(f"seeds {SEEDS}, status {[r['status'] for r in results]}, flags {[r['flags'] for r in results]}")
print(f"peak smoothed acc {peak:.4f} at LR {hist.loc[smooth['test_acc'].idxmax(), 'lr']:.3f}")
print(f"lr_max (smoothed acc >= 90% of peak): {lr_max:.3f}, diverged at LR {diverged_at}")

record_decision(
    "lenet_range_test", runs=[r["name"] for r in results], seeds=list(SEEDS),
    peak_acc=peak, lr_at_peak=hist.loc[smooth["test_acc"].idxmax(), "lr"], lr_max=lr_max,
    lr_max_censored=bool(lr_max >= cfg["lr_hi"] - 1e-6), diverged_at_lr=[round(lr, 4) for lr in diverged_at],
    c11_range=[0.01, 0.1], c11_range_source="paper, Table 2",
)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(hist["lr"], hist["test_acc"], color="tab:blue", alpha=0.3, label="test acc")
axes[0].plot(hist["lr"], smooth["test_acc"], color="tab:blue", label="test acc, rolling mean 5")
axes[0].axvspan(0.01, 0.1, color="tab:green", alpha=0.15, label="1cycle range (paper)")
axes[0].set_xlabel("Learning rate")
axes[0].set_ylabel("Test accuracy")
axes[0].set_title("LR range test, LeNet, MNIST")
axes[0].legend()
axes[1].plot(hist["lr"], hist["train_loss"], label="train loss")
axes[1].plot(hist["lr"], smooth["test_loss"], label="test loss, rolling mean 5")
axes[1].set_yscale("log")
axes[1].set_xlabel("Learning rate")
axes[1].set_ylabel("Loss")
axes[1].legend()
plt.tight_layout()

del results, hist, smooth

results_inv, results_oc = [], []
for s in SEEDS:
    cfg = dict(exp="c11", model="lenet", sched="inv", lr0=0.01, wd=5e-4, bs=512, iters=85 * MNIST_ITS_PER_EPOCH,
               seed=s, eval_every=MNIST_ITS_PER_EPOCH, ckpt_every=10 * MNIST_ITS_PER_EPOCH, n_classes=10)
    torch.manual_seed(s)
    model = lenet().to(device)
    opt = sgd(model, lr=cfg["lr0"], momentum=0.9, wd=cfg["wd"])
    results_inv.append(train(
        run_name(cfg), cfg, model, opt, LambdaLR(opt, lambda it: (1 + 1e-4 * it) ** -0.75),
        make_gpu_loader(gpu_mnist_train, cfg["bs"], train=True), mnist_test_loader, mnist_test_loader,
    ))
    del model, opt

    cfg = dict(exp="c11", model="lenet", sched="1cycle", lr_hi=0.1, wd=5e-4, bs=512, iters=12 * MNIST_ITS_PER_EPOCH,
               seed=s, eval_every=MNIST_ITS_PER_EPOCH, ckpt_every=10 * MNIST_ITS_PER_EPOCH, n_classes=10)
    torch.manual_seed(s)
    model = lenet().to(device)
    opt = sgd(model, momentum=0.9, wd=cfg["wd"])
    results_oc.append(train(
        run_name(cfg), cfg, model, opt,
        one_cycle(opt, cfg["iters"], 0.01, cfg["lr_hi"], cycle_frac=10 / 12, m_min=0.8, m_max=0.95),
        make_gpu_loader(gpu_mnist_train, cfg["bs"], train=True), mnist_test_loader, mnist_test_loader,
    ))
    del model, opt

acc_inv = np.array([r["final"]["test_acc"] for r in results_inv])
acc_oc = np.array([r["final"]["test_acc"] for r in results_oc])
diff = acc_oc.mean() - acc_inv.mean()
pooled_std = math.sqrt((acc_inv.var(ddof=1) + acc_oc.var(ddof=1)) / 2) if len(SEEDS) > 1 else float("nan")
c11 = bool(diff > 2 * pooled_std) if len(SEEDS) >= 3 else None

print(f"{'':12} {'ours':>16} {'paper':>14}")
print(f"{'inv, 85 ep':12} {100 * acc_inv.mean():8.2f} ± {100 * acc_inv.std():.2f} {'99.03 ± 0.04':>14}")
print(f"{'1cycle, 12':12} {100 * acc_oc.mean():8.2f} ± {100 * acc_oc.std():.2f} {'99.25 ± 0.03':>14}")
print(f"difference {100 * diff:.2f} pp, 2 pooled std {200 * pooled_std:.2f} pp, C11 reproduced: {c11}")

record_decision(
    "c11", seeds=list(SEEDS), inv_85=[float(a) for a in acc_inv], one_cycle_12=[float(a) for a in acc_oc],
    diff=diff, pooled_std=pooled_std, c11=c11,
)

fig, ax = plt.subplots(figsize=(7, 4))
for label, results, color in (("inv, 85 epochs", results_inv, "tab:gray"), ("1cycle 0.01-0.1, 12 epochs", results_oc, "tab:red")):
    h = mean_history(results)
    ax.plot(h.index / MNIST_ITS_PER_EPOCH, 100 * (1 - h["test_acc"]), color=color, label=label)
ax.set_yscale("log")
ax.set_xlabel("Epoch")
ax.set_ylabel("Test error, %")
ax.set_title("LeNet on MNIST (Table 2)")
ax.legend()
plt.tight_layout()

del results_inv, results_oc, results, mnist_test_loader, h
gc.collect()
torch.cuda.empty_cache()

"""## experiment 4: 1 cycle vs pc-lr on resnet54"""

lr_max = json.loads((RESULTS / "decisions.json").read_text())["resnet56_range_test"]["lr_max"]
runs_c2 = {"1cycle@3k": [], "PC-LR@3k": [], "PC-LR@24k": []}
for s in SEEDS:
    for key, sched, iters in (("1cycle@3k", "1cycle", 3000), ("PC-LR@3k", "pc", 3000), ("PC-LR@24k", "pc", 24000)):
        cfg = dict(exp="c2", model="resnet", depth=56, n_train=50_000, sched=sched, wd=1e-4, bs=512, iters=iters,
                   seed=s, eval_every=100 if iters <= 3000 else 500, ckpt_every=1000, n_classes=10)
        if sched == "1cycle":
            cfg["lr_hi"] = lr_max
        else:
            cfg["lr0"] = 0.35
        torch.manual_seed(s)
        model = cifar_resnet(cfg["depth"], bn_momentum=0.05).to(device, memory_format=torch.channels_last)
        opt = sgd(model, momentum=0.9, wd=cfg["wd"])
        scheduler = (one_cycle(opt, iters, 0.1, lr_max) if sched == "1cycle"
                     else piecewise_constant(opt, iters, cfg["lr0"]))
        runs_c2[key].append(train(
            run_name(cfg), cfg, model, opt, scheduler,
            make_gpu_loader(gpu_cifar_train, cfg["bs"], train=True, augment=cifar_augment),
            make_gpu_loader(eval_subset, 1000, train=False),
            make_gpu_loader(gpu_cifar_test, 1000, train=False),
        ))
        del model, opt, scheduler

        if key == "PC-LR@3k":
            one, pc = runs_c2["1cycle@3k"][-1], runs_c2["PC-LR@3k"][-1]
            if one["final"]["test_acc"] < pc["final"]["test_acc"]:
                raise RuntimeError(
                    f"sanity bar, seed {s}: 1cycle@3k {one['final']['test_acc']:.4f} < PC-LR@3k "
                    f"{pc['final']['test_acc']:.4f} (flags {one['flags']} / {pc['flags']}); debug before PC-LR@24k"
                )

acc = {key: np.array([r["final"]["test_acc"] for r in results]) for key, results in runs_c2.items()}
paper = {"1cycle@3k": "92.4 (10k)", "PC-LR@3k": "-", "PC-LR@24k": "91.2 (80k)"}
for key, a in acc.items():
    print(f"{key:10} {100 * a.mean():6.2f} ± {100 * a.std():.2f}   paper {paper[key]}")
c2 = bool(acc["1cycle@3k"].mean() >= acc["PC-LR@24k"].mean()
          and acc["1cycle@3k"].mean() - acc["PC-LR@3k"].mean() > 0.01)
print(f"C2 reproduced: {c2}")

record_decision(
    "c2", seeds=list(SEEDS), lr_max=lr_max, **{key: [float(x) for x in a] for key, a in acc.items()},
    flags={key: [r["flags"] for r in results] for key, results in runs_c2.items()}, c2=c2,
)

fig, ax = plt.subplots(figsize=(8, 4.5))
for key, color in (("1cycle@3k", "tab:red"), ("PC-LR@3k", "tab:blue"), ("PC-LR@24k", "tab:gray")):
    h = mean_history(runs_c2[key])
    ax.plot(h.index, h["test_acc"], color=color, label=key)
ax.set_xscale("log")
ax.set_xlabel("Iteration")
ax.set_ylabel("Test accuracy (2k subset)")
ax.set_title("ResNet-56 on CIFAR-10: 1cycle vs PC-LR (Fig. 1a)")
ax.legend()
plt.tight_layout()

del runs_c2, acc, h
gc.collect()
torch.cuda.empty_cache()

